exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings, flake8-debugger, flake8-bugbear, mccabe]
      args: [--max-complexity, "10"]
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.0' # Update me!
    hooks:
    - id: bandit
      args: [-x, satpy/tests]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910-1'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy

